### ISSUE TITLE
How to Modify Training and Testing Image Size

### ISSUE THREAD

**Issue by ferric123** [lim-anggun/FgSegNet#13]
Is it possible to use arbitrary image size for training and testing? In your test_prediction_demo,the input image size must be(240, 320, 3), how can I modify it to test an arbitrary image? Thanks a lot!

**Comment by lim-anggun** [comment]
Hi @ferric123 ,
The model we provided was trained using fixed size images (highway scene), the model input size cannot be changed. This model can be only tested with highway frames to obtained good results (since it's a scene-specific model).

If you just want to test, another way is to resize your training images to (240, 320, 3), where 240 is the height, 320 is the width. Then, after you get the prediction results, you can resize them back to the original size.
Hope that this could help.
