### ISSUE TITLE
Question of Modify the following file

### ISSUE THREAD

**Issue by TDHworkspace** [lim-anggun/FgSegNet#14]
Hi , i have find the file "pyramids.py" and find the function "pyramid_reduce",but i didn't find the line of
 "out_rows = math.ceil(rows / float(downscale)) 
out_cols = math.ceil(cols / float(downscale)) ",any soluvation,thanks

**Comment by nankeermeng** [comment]
python3.6 has "out_rows = math.ceil(rows / float(downscale)),but i do not know how to test image

**Comment by lim-anggun** [comment]
Hi, @TDHworkspace , what python version are you using? Python 3.6 should fixed the error. 
_Feel free to reopen this issue if needed._

**Comment by SidraHanif180** [comment]
Hi @TDHworkspace @nankeermeng 
If you could use the previous version of scikit-image (such as scikit-image 0.11.2), it has the following lines
out_rows = math.ceil(rows / float(downscale))
out_cols = math.ceil(cols / float(downscale))

In my case, I installed scikit-image 0.15.0 because it is compatible with my conda environment and then replace the function from scikit-image 0.11.2 file to the one in my installed directory. This resolves the issue for me.
